version: '2'
services:
  mongo:
    image: mongo
  node:
    build: docker/node
    user: node
    working_dir: /home/node/app
    volumes:
      - ./app:/home/node/app
    ports:
      - 8080:8080
    command: nodemon -L index.js
